# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import xiaoling_pb2 as xiaoling__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xiaoling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XiaoLingStub:
    """小凌 v0.0.1：Flutter(UI) + Python(AI后端) + gRPC(通信) 混合架构
    Flutter 客户端通过 localhost:50051 与 Python 后端通信。

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/xiaoling.XiaoLing/Chat',
                request_serializer=xiaoling__pb2.ChatRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/xiaoling.XiaoLing/GetStatus',
                request_serializer=xiaoling__pb2.StatusRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetGrowthStatus = channel.unary_unary(
                '/xiaoling.XiaoLing/GetGrowthStatus',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.GrowthStatusReply.FromString,
                _registered_method=True)
        self.GetTrainingStatus = channel.unary_unary(
                '/xiaoling.XiaoLing/GetTrainingStatus',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.TrainingStatusReply.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/xiaoling.XiaoLing/ListPlugins',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.PluginList.FromString,
                _registered_method=True)
        self.EnablePlugin = channel.unary_unary(
                '/xiaoling.XiaoLing/EnablePlugin',
                request_serializer=xiaoling__pb2.PluginToggleRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.DisablePlugin = channel.unary_unary(
                '/xiaoling.XiaoLing/DisablePlugin',
                request_serializer=xiaoling__pb2.PluginToggleRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.StartTraining = channel.unary_stream(
                '/xiaoling.XiaoLing/StartTraining',
                request_serializer=xiaoling__pb2.TrainingRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.TrainingProgress.FromString,
                _registered_method=True)
        self.GetTrainingHistory = channel.unary_unary(
                '/xiaoling.XiaoLing/GetTrainingHistory',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.TrainingHistoryReply.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/xiaoling.XiaoLing/ListModels',
                request_serializer=xiaoling__pb2.ListRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.ModelList.FromString,
                _registered_method=True)
        self.SwitchModel = channel.unary_unary(
                '/xiaoling.XiaoLing/SwitchModel',
                request_serializer=xiaoling__pb2.SwitchModelRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ListActions = channel.unary_unary(
                '/xiaoling.XiaoLing/ListActions',
                request_serializer=xiaoling__pb2.ListRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.ActionList.FromString,
                _registered_method=True)
        self.PlayAction = channel.unary_unary(
                '/xiaoling.XiaoLing/PlayAction',
                request_serializer=xiaoling__pb2.PlayActionRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/xiaoling.XiaoLing/ExecuteCommand',
                request_serializer=xiaoling__pb2.CommandRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/xiaoling.XiaoLing/Shutdown',
                request_serializer=xiaoling__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.DetectHardware = channel.unary_unary(
                '/xiaoling.XiaoLing/DetectHardware',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.HardwareInfo.FromString,
                _registered_method=True)
        self.ListRecommendedModels = channel.unary_unary(
                '/xiaoling.XiaoLing/ListRecommendedModels',
                request_serializer=xiaoling__pb2.HardwareRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.RecommendedModelList.FromString,
                _registered_method=True)
        self.DownloadModel = channel.unary_stream(
                '/xiaoling.XiaoLing/DownloadModel',
                request_serializer=xiaoling__pb2.DownloadRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.DownloadProgress.FromString,
                _registered_method=True)
        self.ListInstalledModels = channel.unary_unary(
                '/xiaoling.XiaoLing/ListInstalledModels',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.ModelList.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/xiaoling.XiaoLing/DeleteModel',
                request_serializer=xiaoling__pb2.ModelNameRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ListVoices = channel.unary_unary(
                '/xiaoling.XiaoLing/ListVoices',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.VoiceList.FromString,
                _registered_method=True)
        self.SetVoice = channel.unary_unary(
                '/xiaoling.XiaoLing/SetVoice',
                request_serializer=xiaoling__pb2.VoiceRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ReadAloud = channel.unary_stream(
                '/xiaoling.XiaoLing/ReadAloud',
                request_serializer=xiaoling__pb2.ReadRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.GetSettings = channel.unary_unary(
                '/xiaoling.XiaoLing/GetSettings',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.SettingsReply.FromString,
                _registered_method=True)
        self.UpdateSettings = channel.unary_unary(
                '/xiaoling.XiaoLing/UpdateSettings',
                request_serializer=xiaoling__pb2.SettingsRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ExportData = channel.unary_unary(
                '/xiaoling.XiaoLing/ExportData',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.DataBlob.FromString,
                _registered_method=True)
        self.ImportData = channel.unary_unary(
                '/xiaoling.XiaoLing/ImportData',
                request_serializer=xiaoling__pb2.DataBlob.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetPersona = channel.unary_unary(
                '/xiaoling.XiaoLing/GetPersona',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.PersonaReply.FromString,
                _registered_method=True)
        self.ListPersonas = channel.unary_unary(
                '/xiaoling.XiaoLing/ListPersonas',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.PersonaList.FromString,
                _registered_method=True)
        self.SetPersona = channel.unary_unary(
                '/xiaoling.XiaoLing/SetPersona',
                request_serializer=xiaoling__pb2.PersonaRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.AddPersona = channel.unary_unary(
                '/xiaoling.XiaoLing/AddPersona',
                request_serializer=xiaoling__pb2.PersonaRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.DeletePersona = channel.unary_unary(
                '/xiaoling.XiaoLing/DeletePersona',
                request_serializer=xiaoling__pb2.ModelNameRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ResetPersona = channel.unary_unary(
                '/xiaoling.XiaoLing/ResetPersona',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ListReminders = channel.unary_unary(
                '/xiaoling.XiaoLing/ListReminders',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.ReminderList.FromString,
                _registered_method=True)
        self.CompleteReminder = channel.unary_unary(
                '/xiaoling.XiaoLing/CompleteReminder',
                request_serializer=xiaoling__pb2.ReminderRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.AgentStart = channel.unary_stream(
                '/xiaoling.XiaoLing/AgentStart',
                request_serializer=xiaoling__pb2.AgentRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.AgentEvent.FromString,
                _registered_method=True)
        self.TerminalCreate = channel.unary_unary(
                '/xiaoling.XiaoLing/TerminalCreate',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.TerminalSession.FromString,
                _registered_method=True)
        self.TerminalWrite = channel.unary_unary(
                '/xiaoling.XiaoLing/TerminalWrite',
                request_serializer=xiaoling__pb2.TerminalInput.SerializeToString,
                response_deserializer=xiaoling__pb2.Empty.FromString,
                _registered_method=True)
        self.TerminalRead = channel.unary_stream(
                '/xiaoling.XiaoLing/TerminalRead',
                request_serializer=xiaoling__pb2.TerminalSessionId.SerializeToString,
                response_deserializer=xiaoling__pb2.TerminalOutput.FromString,
                _registered_method=True)
        self.TerminalClose = channel.unary_unary(
                '/xiaoling.XiaoLing/TerminalClose',
                request_serializer=xiaoling__pb2.TerminalSessionId.SerializeToString,
                response_deserializer=xiaoling__pb2.Empty.FromString,
                _registered_method=True)
        self.FileList = channel.unary_unary(
                '/xiaoling.XiaoLing/FileList',
                request_serializer=xiaoling__pb2.FileListRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.FileListReply.FromString,
                _registered_method=True)
        self.FileRead = channel.unary_unary(
                '/xiaoling.XiaoLing/FileRead',
                request_serializer=xiaoling__pb2.FileReadRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.FileContent.FromString,
                _registered_method=True)
        self.FileWrite = channel.unary_unary(
                '/xiaoling.XiaoLing/FileWrite',
                request_serializer=xiaoling__pb2.FileWriteRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.CodeSearch = channel.unary_unary(
                '/xiaoling.XiaoLing/CodeSearch',
                request_serializer=xiaoling__pb2.CodeSearchRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.CodeSearchReply.FromString,
                _registered_method=True)
        self.ProjectContext = channel.unary_unary(
                '/xiaoling.XiaoLing/ProjectContext',
                request_serializer=xiaoling__pb2.Empty.SerializeToString,
                response_deserializer=xiaoling__pb2.ProjectContextReply.FromString,
                _registered_method=True)


class XiaoLingServicer:
    """小凌 v0.0.1：Flutter(UI) + Python(AI后端) + gRPC(通信) 混合架构
    Flutter 客户端通过 localhost:50051 与 Python 后端通信。

    """

    def Chat(self, request, context):
        """===== 对话 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """===== 状态 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGrowthStatus(self, request, context):
        """===== 成长 / 训练（Flutter 可视化） =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """===== 插件系统 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnablePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisablePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTraining(self, request, context):
        """===== 启动训练（流式进度） =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """===== 模型管理 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActions(self, request, context):
        """===== 动作 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """===== 指令 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """===== 关闭 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectHardware(self, request, context):
        """===== 硬件检测 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRecommendedModels(self, request, context):
        """===== 智能模型推荐 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModel(self, request, context):
        """===== 模型下载（流式进度） =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstalledModels(self, request, context):
        """===== 列出已安装模型 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """===== 删除模型 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVoices(self, request, context):
        """===== 音色列表 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVoice(self, request, context):
        """===== 切换音色 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAloud(self, request, context):
        """===== 语音朗读（流式音频） =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSettings(self, request, context):
        """===== 读取设置 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSettings(self, request, context):
        """===== 更新设置 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportData(self, request, context):
        """===== 数据导出 / 导入 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPersona(self, request, context):
        """===== 人格画像（情绪 / 亲密度 / 等级） =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPersonas(self, request, context):
        """===== 人格预设列表（5 个内置 + 用户自定义） =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPersona(self, request, context):
        """===== 切换人格预设 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPersona(self, request, context):
        """===== 新增自定义人格 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePersona(self, request, context):
        """===== 删除自定义人格 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPersona(self, request, context):
        """===== 重置人格画像（情绪/亲密度清零） =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReminders(self, request, context):
        """===== 提醒队列（含未读提醒，铃铛面板用） =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteReminder(self, request, context):
        """===== 标记提醒已读 / 完成 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentStart(self, request, context):
        """===== Agent 自主任务模式 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminalCreate(self, request, context):
        """===== 内置终端 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminalWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminalRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminalClose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileList(self, request, context):
        """===== 文件操作 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CodeSearch(self, request, context):
        """===== 代码搜索 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProjectContext(self, request, context):
        """===== 项目上下文 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XiaoLingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=xiaoling__pb2.ChatRequest.FromString,
                    response_serializer=xiaoling__pb2.ChatChunk.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=xiaoling__pb2.StatusRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'GetGrowthStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGrowthStatus,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.GrowthStatusReply.SerializeToString,
            ),
            'GetTrainingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStatus,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.TrainingStatusReply.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.PluginList.SerializeToString,
            ),
            'EnablePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.EnablePlugin,
                    request_deserializer=xiaoling__pb2.PluginToggleRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'DisablePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.DisablePlugin,
                    request_deserializer=xiaoling__pb2.PluginToggleRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'StartTraining': grpc.unary_stream_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=xiaoling__pb2.TrainingRequest.FromString,
                    response_serializer=xiaoling__pb2.TrainingProgress.SerializeToString,
            ),
            'GetTrainingHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingHistory,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.TrainingHistoryReply.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=xiaoling__pb2.ListRequest.FromString,
                    response_serializer=xiaoling__pb2.ModelList.SerializeToString,
            ),
            'SwitchModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchModel,
                    request_deserializer=xiaoling__pb2.SwitchModelRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'ListActions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActions,
                    request_deserializer=xiaoling__pb2.ListRequest.FromString,
                    response_serializer=xiaoling__pb2.ActionList.SerializeToString,
            ),
            'PlayAction': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayAction,
                    request_deserializer=xiaoling__pb2.PlayActionRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=xiaoling__pb2.CommandRequest.FromString,
                    response_serializer=xiaoling__pb2.CommandReply.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=xiaoling__pb2.ShutdownRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'DetectHardware': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectHardware,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.HardwareInfo.SerializeToString,
            ),
            'ListRecommendedModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRecommendedModels,
                    request_deserializer=xiaoling__pb2.HardwareRequest.FromString,
                    response_serializer=xiaoling__pb2.RecommendedModelList.SerializeToString,
            ),
            'DownloadModel': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=xiaoling__pb2.DownloadRequest.FromString,
                    response_serializer=xiaoling__pb2.DownloadProgress.SerializeToString,
            ),
            'ListInstalledModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstalledModels,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.ModelList.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=xiaoling__pb2.ModelNameRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'ListVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVoices,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.VoiceList.SerializeToString,
            ),
            'SetVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVoice,
                    request_deserializer=xiaoling__pb2.VoiceRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'ReadAloud': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadAloud,
                    request_deserializer=xiaoling__pb2.ReadRequest.FromString,
                    response_serializer=xiaoling__pb2.AudioChunk.SerializeToString,
            ),
            'GetSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSettings,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.SettingsReply.SerializeToString,
            ),
            'UpdateSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSettings,
                    request_deserializer=xiaoling__pb2.SettingsRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'ExportData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportData,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.DataBlob.SerializeToString,
            ),
            'ImportData': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportData,
                    request_deserializer=xiaoling__pb2.DataBlob.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'GetPersona': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPersona,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.PersonaReply.SerializeToString,
            ),
            'ListPersonas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPersonas,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.PersonaList.SerializeToString,
            ),
            'SetPersona': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPersona,
                    request_deserializer=xiaoling__pb2.PersonaRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'AddPersona': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPersona,
                    request_deserializer=xiaoling__pb2.PersonaRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'DeletePersona': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePersona,
                    request_deserializer=xiaoling__pb2.ModelNameRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'ResetPersona': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPersona,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'ListReminders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReminders,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.ReminderList.SerializeToString,
            ),
            'CompleteReminder': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteReminder,
                    request_deserializer=xiaoling__pb2.ReminderRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'AgentStart': grpc.unary_stream_rpc_method_handler(
                    servicer.AgentStart,
                    request_deserializer=xiaoling__pb2.AgentRequest.FromString,
                    response_serializer=xiaoling__pb2.AgentEvent.SerializeToString,
            ),
            'TerminalCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminalCreate,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.TerminalSession.SerializeToString,
            ),
            'TerminalWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminalWrite,
                    request_deserializer=xiaoling__pb2.TerminalInput.FromString,
                    response_serializer=xiaoling__pb2.Empty.SerializeToString,
            ),
            'TerminalRead': grpc.unary_stream_rpc_method_handler(
                    servicer.TerminalRead,
                    request_deserializer=xiaoling__pb2.TerminalSessionId.FromString,
                    response_serializer=xiaoling__pb2.TerminalOutput.SerializeToString,
            ),
            'TerminalClose': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminalClose,
                    request_deserializer=xiaoling__pb2.TerminalSessionId.FromString,
                    response_serializer=xiaoling__pb2.Empty.SerializeToString,
            ),
            'FileList': grpc.unary_unary_rpc_method_handler(
                    servicer.FileList,
                    request_deserializer=xiaoling__pb2.FileListRequest.FromString,
                    response_serializer=xiaoling__pb2.FileListReply.SerializeToString,
            ),
            'FileRead': grpc.unary_unary_rpc_method_handler(
                    servicer.FileRead,
                    request_deserializer=xiaoling__pb2.FileReadRequest.FromString,
                    response_serializer=xiaoling__pb2.FileContent.SerializeToString,
            ),
            'FileWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.FileWrite,
                    request_deserializer=xiaoling__pb2.FileWriteRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'CodeSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.CodeSearch,
                    request_deserializer=xiaoling__pb2.CodeSearchRequest.FromString,
                    response_serializer=xiaoling__pb2.CodeSearchReply.SerializeToString,
            ),
            'ProjectContext': grpc.unary_unary_rpc_method_handler(
                    servicer.ProjectContext,
                    request_deserializer=xiaoling__pb2.Empty.FromString,
                    response_serializer=xiaoling__pb2.ProjectContextReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xiaoling.XiaoLing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xiaoling.XiaoLing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XiaoLing:
    """小凌 v0.0.1：Flutter(UI) + Python(AI后端) + gRPC(通信) 混合架构
    Flutter 客户端通过 localhost:50051 与 Python 后端通信。

    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xiaoling.XiaoLing/Chat',
            xiaoling__pb2.ChatRequest.SerializeToString,
            xiaoling__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/GetStatus',
            xiaoling__pb2.StatusRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGrowthStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/GetGrowthStatus',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.GrowthStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/GetTrainingStatus',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.TrainingStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListPlugins',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.PluginList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnablePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/EnablePlugin',
            xiaoling__pb2.PluginToggleRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisablePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/DisablePlugin',
            xiaoling__pb2.PluginToggleRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xiaoling.XiaoLing/StartTraining',
            xiaoling__pb2.TrainingRequest.SerializeToString,
            xiaoling__pb2.TrainingProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/GetTrainingHistory',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.TrainingHistoryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListModels',
            xiaoling__pb2.ListRequest.SerializeToString,
            xiaoling__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/SwitchModel',
            xiaoling__pb2.SwitchModelRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListActions',
            xiaoling__pb2.ListRequest.SerializeToString,
            xiaoling__pb2.ActionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/PlayAction',
            xiaoling__pb2.PlayActionRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ExecuteCommand',
            xiaoling__pb2.CommandRequest.SerializeToString,
            xiaoling__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/Shutdown',
            xiaoling__pb2.ShutdownRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectHardware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/DetectHardware',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.HardwareInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRecommendedModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListRecommendedModels',
            xiaoling__pb2.HardwareRequest.SerializeToString,
            xiaoling__pb2.RecommendedModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xiaoling.XiaoLing/DownloadModel',
            xiaoling__pb2.DownloadRequest.SerializeToString,
            xiaoling__pb2.DownloadProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstalledModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListInstalledModels',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/DeleteModel',
            xiaoling__pb2.ModelNameRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListVoices',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.VoiceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/SetVoice',
            xiaoling__pb2.VoiceRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadAloud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xiaoling.XiaoLing/ReadAloud',
            xiaoling__pb2.ReadRequest.SerializeToString,
            xiaoling__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/GetSettings',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.SettingsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/UpdateSettings',
            xiaoling__pb2.SettingsRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ExportData',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.DataBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ImportData',
            xiaoling__pb2.DataBlob.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/GetPersona',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.PersonaReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPersonas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListPersonas',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.PersonaList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/SetPersona',
            xiaoling__pb2.PersonaRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/AddPersona',
            xiaoling__pb2.PersonaRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/DeletePersona',
            xiaoling__pb2.ModelNameRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ResetPersona',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReminders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListReminders',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.ReminderList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteReminder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/CompleteReminder',
            xiaoling__pb2.ReminderRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xiaoling.XiaoLing/AgentStart',
            xiaoling__pb2.AgentRequest.SerializeToString,
            xiaoling__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminalCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/TerminalCreate',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.TerminalSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminalWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/TerminalWrite',
            xiaoling__pb2.TerminalInput.SerializeToString,
            xiaoling__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminalRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xiaoling.XiaoLing/TerminalRead',
            xiaoling__pb2.TerminalSessionId.SerializeToString,
            xiaoling__pb2.TerminalOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminalClose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/TerminalClose',
            xiaoling__pb2.TerminalSessionId.SerializeToString,
            xiaoling__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/FileList',
            xiaoling__pb2.FileListRequest.SerializeToString,
            xiaoling__pb2.FileListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/FileRead',
            xiaoling__pb2.FileReadRequest.SerializeToString,
            xiaoling__pb2.FileContent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/FileWrite',
            xiaoling__pb2.FileWriteRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CodeSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/CodeSearch',
            xiaoling__pb2.CodeSearchRequest.SerializeToString,
            xiaoling__pb2.CodeSearchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProjectContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ProjectContext',
            xiaoling__pb2.Empty.SerializeToString,
            xiaoling__pb2.ProjectContextReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
