name: deploy-pages
on:
  push:
    branches: [main]
    paths: ['index.html', 'assets/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: cfat_kzb7DGi0fCBvwYNu0dezr0nivw9ZIr5dUtoq9bc5c5bdaf
          accountId: 7d3b4e416b91633180e454de0988daa0
          command: pages deploy . --project-name=xiaoling-4o6
